name: iot_mqtt
description: "Flutter app for IoT device control and monitoring via MQTT"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  # MQTT client for Flutter 
  mqtt_client: ^10.2.0 
  speech_to_text: ^6.6.0
   
  # For JSON handling 
  http: ^1.1.0 
 
  # UI Components 
  cupertino_icons: ^1.0.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true